#!/bin/bash
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-agreements-1.0.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_agreements-1.1.3
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_calendar-2.0.6
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_checkin-1.4.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_checkout-1.5.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_circulation-1.4.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_data-import-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_developer-1.6.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_eholdings-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_erm-usage-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_finance-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_inventory-1.5.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_licenses-1.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_marccat-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_myprofile-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_orders-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_organization-2.6.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_plugin-find-instance-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_plugin-find-user-1.4.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_plugin-find-vendor-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_requests-1.6.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_search-1.4.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_servicepoints-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_stripes-core-2.17.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_stripes-smart-components-1.12.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_tags-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_users-2.19.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/folio_vendors-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-agreements-1.0.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-audit-0.0.3
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-audit-filter-0.0.3
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-authtoken-2.0.4
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-calendar-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-circulation-14.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-circulation-storage-6.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-codex-ekb-1.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-codex-inventory-1.4.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-codex-mux-2.3.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-configuration-5.0.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-data-import-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-email-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-erm-usage-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-erm-usage-harvester-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-event-config-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-feesfines-15.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-finance-storage-1.0.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-gobi-1.0.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-inventory-11.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-inventory-storage-14.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-kb-ebsco-1.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-licenses-1.0.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-login-4.6.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-login-saml-1.2.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-marccat-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-notes-2.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-notify-2.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-oai-pmh-1.0.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-orders-1.0.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-orders-storage-1.0.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-password-validator-1.0.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-patron-1.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-permissions-5.4.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-rtac-1.2.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-sender-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-source-record-manager-0.1.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-source-record-storage-1.0.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-tags-0.2.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-template-engine-1.0.1
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-users-15.3.0
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-users-bl-4.3.2
curl -w '\n' -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-vendors-1.0.3
